# Generated by Django 4.0.5 on 2022-08-19 13:45

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=32)),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('town_or_city', models.CharField(max_length=40)),
                ('street_address1', models.CharField(max_length=80)),
                ('street_address2', models.CharField(blank=True, max_length=80, null=True)),
                ('county', models.CharField(blank=True, max_length=80, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('order_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stripe_pid', models.CharField(default='', max_length=254)),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='accounts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.category')),
            ],
            options={
                'verbose_name_plural': 'Subcategories',
            },
        ),
        migrations.CreateModel(
            name='Property_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(max_length=254)),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.subcategory')),
            ],
            options={
                'verbose_name': 'Property Type',
                'verbose_name_plural': 'Property Types',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Name is empty', max_length=254)),
                ('description', models.TextField(default='Please provide description')),
                ('price', models.PositiveIntegerField(default='0')),
                ('period', models.CharField(blank=True, max_length=254, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('primary_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('detail_image1', models.ImageField(blank=True, null=True, upload_to='')),
                ('detail_image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('detail_image3', models.ImageField(blank=True, null=True, upload_to='')),
                ('detail_image4', models.ImageField(blank=True, null=True, upload_to='')),
                ('detail_image5', models.ImageField(blank=True, null=True, upload_to='')),
                ('detail_image6', models.ImageField(blank=True, null=True, upload_to='')),
                ('detail_image7', models.ImageField(blank=True, null=True, upload_to='')),
                ('detail_image8', models.ImageField(blank=True, null=True, upload_to='')),
                ('detail_image9', models.ImageField(blank=True, null=True, upload_to='')),
                ('detail_image10', models.ImageField(blank=True, null=True, upload_to='')),
                ('detail_image11', models.ImageField(blank=True, null=True, upload_to='')),
                ('detail_image12', models.ImageField(blank=True, null=True, upload_to='')),
                ('town', models.CharField(default='Please specify town', max_length=254)),
                ('address', models.CharField(default='Please provide the address', max_length=254)),
                ('post_code', models.CharField(default='Please specify post code', max_length=254)),
                ('bedroom', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('bathroom', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('reception', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('adults', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('children', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('rooms', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('available', models.BooleanField(blank=True, default=True, null=True)),
                ('rented', models.BooleanField(blank=True, default=False, null=True)),
                ('sold', models.BooleanField(blank=True, default=False, null=True)),
                ('available_from', models.CharField(blank=True, max_length=256, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.category')),
                ('property_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.property_type')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('lineitem_total', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineitems', to='store.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
