# Generated by Django 4.0.5 on 2022-07-18 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_adults_product_available_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property_type',
            options={'verbose_name': 'Property Type', 'verbose_name_plural': 'Property Types'},
        ),
    ]
