# Generated by Django 4.0.5 on 2022-07-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_beds_product_bedroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='period',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
