# Generated by Django 4.0.5 on 2022-07-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detail_image11',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='detail_image12',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
